#!/usr/bin/env node
"use strict";

// Builds the deployable site into dist/: the web app from src/, plus the
// browser bundles generated from the canonical content in content/. dist/ is
// build output and is never committed; GitHub Pages deploys it from CI.

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const DIST = path.join(ROOT, "dist");

const { TEMPLATE_SECTIONS, familyFiles } = require("./lib/families");

fs.rmSync(DIST, { recursive: true, force: true });
// Template sources are organized for people (one file per skill); the
// browser gets one bundle per section instead, written below.
const FAMILY_SOURCES = path.join(ROOT, "src", "lib", "families");
fs.cpSync(path.join(ROOT, "src"), DIST, {
  recursive: true,
  filter: (source) => !source.startsWith(FAMILY_SOURCES),
});
fs.mkdirSync(path.join(DIST, "lib", "families"), { recursive: true });
TEMPLATE_SECTIONS.forEach((sectionKey) => {
  const bundle = familyFiles(sectionKey)
    .map((file) => `/* ${path.relative(ROOT, file)} */\n${fs.readFileSync(file, "utf8")}`)
    .join("\n");
  fs.writeFileSync(path.join(DIST, "lib", "families", `${sectionKey}.js`), bundle);
});

// Validates the canonical banks, then writes dist/content/*.js.
require("./build-content");

fs.copyFileSync(
  path.join(ROOT, "content", "guides", "answer-signs.js"),
  path.join(DIST, "content", "answer-signs.js"),
);

// Template registries, so the browser can build and decode run masks.
const registries = Object.fromEntries(
  fs.readdirSync(path.join(ROOT, "content", "templates"))
    .filter((file) => file.endsWith(".json"))
    .map((file) => {
      const registry = JSON.parse(fs.readFileSync(path.join(ROOT, "content", "templates", file), "utf8"));
      return [registry.sectionKey, registry];
    }),
);
fs.writeFileSync(
  path.join(DIST, "content", "templates.js"),
  `/* Generated by tools/build.js from content/templates. */\nwindow.PRACTICE_TEMPLATES = ${JSON.stringify(registries)};\n`,
);

// Serve files as they are; GitHub Pages would otherwise run Jekyll.
fs.writeFileSync(path.join(DIST, ".nojekyll"), "");

console.log("Built dist/");
