#!/usr/bin/env node
"use strict";

// Builds the deployable site into dist/: the web app from src/, plus the
// browser bundles generated from the canonical content in content/. dist/ is
// build output and is never committed; GitHub Pages deploys it from CI.

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const DIST = path.join(ROOT, "dist");

const { TEMPLATE_SECTIONS, familyFiles } = require("./lib/families");

// Direct builds must not publish new source under old saved-question versions.
if (require("./update-templates").main(["--check"]) !== 0) {
  throw new Error("Build stopped because template registries are stale");
}

fs.rmSync(DIST, { recursive: true, force: true });
// Template sources are organized for people (one file per skill); the
// browser gets one bundle per section instead, written below.
const FAMILY_SOURCES = path.join(ROOT, "src", "lib", "families");
fs.cpSync(path.join(ROOT, "src"), DIST, {
  recursive: true,
  filter: (source) => !source.startsWith(FAMILY_SOURCES),
});
// Every page gets the one shared header (tools/lib/site-header.js).
const siteHeader = require("./lib/site-header");
fs.readdirSync(DIST).filter((file) => file.endsWith(".html")).forEach((page) => {
  const file = path.join(DIST, page);
  fs.writeFileSync(file, siteHeader.apply(fs.readFileSync(file, "utf8"), page));
});
fs.mkdirSync(path.join(DIST, "lib", "families"), { recursive: true });
TEMPLATE_SECTIONS.forEach((sectionKey) => {
  const bundle = familyFiles(sectionKey)
    .map((file) => `/* ${path.relative(ROOT, file)} */\n${fs.readFileSync(file, "utf8")}`)
    .join("\n");
  fs.writeFileSync(path.join(DIST, "lib", "families", `${sectionKey}.js`), bundle);
});

// Validates the canonical banks, then writes dist/content/*.js.
if (require("./build-content").main() !== 0) {
  throw new Error("Build stopped because content admission failed");
}

fs.copyFileSync(
  path.join(ROOT, "content", "guides", "answer-signs.js"),
  path.join(DIST, "content", "answer-signs.js"),
);

// Template registries, so the browser can build and decode run masks. Each
// live entry also carries its template's current tier, domain, skill and
// subskill, so Progress and Review can re-tier old answers without loading a
// section's whole template bundle.
const FAMILY_INDEX = {
  "sat-math": "../src/lib/families/sat/math",
  "sat-reading-writing": "../src/lib/families/sat/reading-writing",
};
const registries = Object.fromEntries(
  fs.readdirSync(path.join(ROOT, "content", "templates"))
    .filter((file) => file.endsWith(".json"))
    .map((file) => {
      const registry = JSON.parse(fs.readFileSync(path.join(ROOT, "content", "templates", file), "utf8"));
      const families = FAMILY_INDEX[registry.sectionKey] ? require(FAMILY_INDEX[registry.sectionKey]) : [];
      const byId = new Map(families.map((family) => [family.id, family]));
      registry.templates = registry.templates.map((entry) => {
        const family = byId.get(entry.id);
        if (!family || entry.retired) return entry;
        const { difficulty, domain, skill, subskill } = family;
        return { ...entry, difficulty, domain, skill, subskill };
      });
      return [registry.sectionKey, registry];
    }),
);
fs.writeFileSync(
  path.join(DIST, "content", "templates.js"),
  `/* Generated by tools/build.js from content/templates and the templates. */\nwindow.PRACTICE_TEMPLATES = ${JSON.stringify(registries)};\n`,
);

// The Learn pages, parsed and checked, as dist/content/learn-sat.js. A
// missing content/learn/ builds an empty bundle so the rest of the site
// still builds; tools/check-learn.js fails on it.
require("./build-learn").build({ allowMissing: true });

// Classroom courses have their own taxonomy and worksheet generators.
require("./build-courses").build();
require("./build-work-samples").build();
require("./build-curriculum").build();
require("./build-weekly").build();
require("./build-daily-reading").build();
require("./build-reading-level").build();

// Serve files as they are; GitHub Pages would otherwise run Jekyll.
fs.writeFileSync(path.join(DIST, ".nojekyll"), "");

console.log("Built dist/");
