#!/usr/bin/env node
"use strict";

// Builds the AP® assessment data for ap.html after tools/check-ap.js admits it:
//   dist/content/ap.js     window.LIMINAL_AP: an index of the assessments and
//                          references that exist
//   dist/content/ap/assessments/<course>/<id>.json   one document each, with
//                          figure SVG inlined (loaded on demand)
//   dist/content/ap/references/<course>.json
// The plan itself (content/ap.json) is validated and bundled by
// tools/build-weekly.js as the named track's plan: content/ap-plan.js
// (window.LIMINAL_AP_PLAN) and content/ap-plan.json.
// Answer keys ship in the assessment files, as weekly keys do; the page
// separates student and key copies, and print follows the copy on screen.

const fs = require("node:fs");
const path = require("node:path");
const A = require("../src/lib/ap-assessment");
const { loadAp } = require("./check-ap");

const ROOT = path.resolve(__dirname, "..");

function script(name, value) {
  return "/* Generated by tools/build-ap.js from content/ap/. */\nwindow." + name + " = " +
    JSON.stringify(value).replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029") + ";\n";
}

function bundle(result) {
  return {
    version: 1,
    assessments: result.assessments.map(doc => {
      const counts = A.counts(doc);
      return { courseId: doc.courseId, id: doc.id, kind: doc.kind, ...(doc.unitId ? { unitId: doc.unitId } : {}), title: doc.title,
        mc: counts.mc, fr: counts.fr, minutes: counts.minutes, points: counts.points,
        file: "content/ap/assessments/" + doc.courseId + "/" + doc.id + ".json" };
    }),
    references: result.references.map(ref => ({ courseId: ref.courseId, title: ref.title, file: "content/ap/references/" + ref.courseId + ".json" })),
  };
}

function build({ output = path.join(ROOT, "dist"), contentDir, pagesDir } = {}) {
  const result = loadAp({ contentDir, pagesDir });
  if (result.problems.length) {
    throw new Error("AP: " + result.problems.length + " problem(s); run node tools/check-ap.js\n  " + result.problems.slice(0, 10).join("\n  "));
  }
  const directory = path.join(output, "content");
  fs.mkdirSync(directory, { recursive: true });
  fs.rmSync(path.join(directory, "ap"), { recursive: true, force: true });
  const data = bundle(result);
  for (const doc of result.assessments) {
    const target = path.join(directory, "ap", "assessments", doc.courseId, doc.id + ".json");
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, JSON.stringify(doc) + "\n");
  }
  for (const ref of result.references) {
    const target = path.join(directory, "ap", "references", ref.courseId + ".json");
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, JSON.stringify(ref) + "\n");
  }
  fs.writeFileSync(path.join(directory, "ap.js"), script("LIMINAL_AP", data));
  console.log(`Built AP data: ${result.plan.courses.length} course plans, ${result.assessments.length} assessments, ${result.references.length} references.`);
  return data;
}

module.exports = { build, bundle };
if (require.main === module) {
  const option = name => { const i = process.argv.indexOf(name); return i >= 0 ? path.resolve(process.argv[i + 1]) : undefined; };
  build({ output: option("--output"), contentDir: option("--content"), pagesDir: option("--pages") });
}
