#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");
const {
  GENERATED_DIR,
  loadBank,
  loadPassages,
  passageStimulus,
  validateAll,
} = require("./lib/content");

const result = validateAll();
if (result.errors.length > 0) {
  console.error("Build stopped because content validation failed.");
  result.errors.slice(0, 50).forEach((error) => console.error(`- ${error}`));
  process.exit(1);
}

fs.mkdirSync(GENERATED_DIR, { recursive: true });
const catalogOutput = [
  "/* Generated by tools/build-content.js. Edit content/catalog.json instead. */",
  `window.PRACTICE_CATALOG = ${JSON.stringify(result.catalog)};`,
  "",
].join("\n");
fs.writeFileSync(path.join(GENERATED_DIR, "catalog.js"), catalogOutput);

result.catalog.sections.forEach((section) => {
  const bank = loadBank(section.key);
  const passages = loadPassages(section.key);
  const key = JSON.stringify(section.key);

  // Passages ship once and are stitched onto their questions here rather than
  // copied into each one. Ten questions on a 750-word passage then hold ten
  // references to a single object: the download stays the size of the passage,
  // and every existing consumer keeps reading `question.stimulus` unchanged.
  const stimulus = {};
  passages.forEach((passage) => {
    stimulus[passage.id] = passageStimulus(passage);
  });

  const output = [
    "/* Generated by tools/build-content.js. Edit the canonical JSON bank instead. */",
    "window.PRACTICE_PASSAGES = window.PRACTICE_PASSAGES || {};",
    `window.PRACTICE_PASSAGES[${key}] = ${JSON.stringify(passages)};`,
    "window.PRACTICE_BANKS = window.PRACTICE_BANKS || {};",
    `window.PRACTICE_BANKS[${key}] = (function () {`,
    `  var stimulus = ${JSON.stringify(stimulus)};`,
    `  var bank = ${JSON.stringify(bank)};`,
    "  bank.forEach(function (question) {",
    "    if (question.passageId) question.stimulus = stimulus[question.passageId];",
    "  });",
    "  return bank;",
    "}());",
    "",
  ].join("\n");
  fs.writeFileSync(path.join(GENERATED_DIR, `${section.key}.js`), output);
});

console.log(
  `Built ${result.questions.length} validated questions into ${result.catalog.sections.length} banks.`,
);
