#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { GENERATED_DIR, loadRuntimeBank, loadPassages, passageStimulus, validateAll } = require("./lib/content");

// Share each passage's stimulus and figure objects across its set. The archive
// joins only at this runtime boundary: old attempts still resolve without
// inflating admission or coverage counts for the active bank.
function bankBundle(sectionKey, bank, passages) {
  const key = JSON.stringify(sectionKey), stimulus = {}, figures = {};
  passages.forEach((passage) => {
    stimulus[passage.id] = passageStimulus(passage);
    if (passage.figure) figures[passage.id] = passage.figure;
  });
  return [
    "/* Generated by tools/build-content.js. Edit the canonical JSON bank instead. */",
    "window.PRACTICE_PASSAGES = window.PRACTICE_PASSAGES || {};",
    `window.PRACTICE_PASSAGES[${key}] = ${JSON.stringify(passages)};`,
    "window.PRACTICE_BANKS = window.PRACTICE_BANKS || {};",
    `window.PRACTICE_BANKS[${key}] = (function () {`,
    `  var stimulus = ${JSON.stringify(stimulus)};`,
    `  var figures = ${JSON.stringify(figures)};`,
    `  var bank = ${JSON.stringify(bank)};`,
    "  bank.forEach(function (question) {",
    "    if (question.passageId) question.stimulus = stimulus[question.passageId];",
    "    if (question.passageId && figures[question.passageId]) question.figure = figures[question.passageId];",
    "  });",
    "  return bank;",
    "}());", "",
  ].join("\n");
}
function main() {
  const result = validateAll();
  if (result.errors.length > 0) {
    console.error("Build stopped because content validation failed.");
    result.errors.slice(0, 50).forEach((error) => console.error(`- ${error}`));
    return 1;
  }
  if (result.catalog.sections.some((section) => section.key === "act-science" && section.practiceAvailable !== false)) {
    if (require("./check-science").main() !== 0) return 1;
  }
  fs.mkdirSync(GENERATED_DIR, { recursive: true });
  fs.writeFileSync(path.join(GENERATED_DIR, "catalog.js"), [
    "/* Generated by tools/build-content.js. Edit content/catalog.json instead. */",
    `window.PRACTICE_CATALOG = ${JSON.stringify(result.catalog)};`, "",
  ].join("\n"));
  result.catalog.sections.forEach((section) => {
    fs.writeFileSync(path.join(GENERATED_DIR, `${section.key}.js`),
      bankBundle(section.key, loadRuntimeBank(section.key), loadPassages(section.key)));
  });
  console.log(`Built ${result.questions.length} bank records and ${result.archiveQuestions.length} separately archived records into ${result.catalog.sections.length} bundles.`);
  return 0;
}
if (require.main === module) process.exitCode = main();
module.exports = { bankBundle, main };
